apiVersion: v1
kind: Service
metadata:
  name: grafana2whatsapp-svc
  namespace: grafana2whatsapp
spec:
  selector:
    app: grafana2whatsapp
  ports:
    - name: metrics
      port: 80
      targetPort: 5000
  type: ClusterIP
