env:
  - name: TZ
    value: "America/Sao_Paulo"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
