apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati-config
  namespace: duplicati
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 300Mi