apiVersion: v1
kind: Service
metadata:
  name: duplicati
  namespace: duplicati
spec:
  type: ClusterIP
  selector:
    app: duplicati
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
      name: http