env:
  TZ: America/Sao_Paulo

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
  media:
    enabled: false

volumes:
  - name: media-volume
    hostPath:
      path: /mnt/data
      type: DirectoryOrCreate

volumeMounts:
  - name: media-volume
    mountPath: /data

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
