apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-dp
  namespace: adguard
  labels:
    app: adguardhome
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: adguardhome
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      containers:
      - name: adguardhome
        image: adguard/adguardhome:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - DAC_OVERRIDE
        env:
          - name: TZ
            value: America/Sao_Paulo
        resources:
          limits:
            cpu: "300m"
            memory: 2Gi
          requests:
            cpu: "30m"
            memory: 768Mi
        ports:
          - containerPort: 80
            name: http
          - containerPort: 53
            protocol: TCP
            name: dns-tcp
          - containerPort: 53
            protocol: UDP
            name: dns-udp
        volumeMounts:
          - name: work
            mountPath: /opt/adguardhome/work
          - name: config
            mountPath: /opt/adguardhome/conf
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work-pvc
        - name: config
          persistentVolumeClaim:
            claimName: adguard-config-pvc
