apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatsapp-sessions-pvc
  namespace: discord2whatsapp-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
