
steam:
  enabled: false
firefox:
  enabled: false


retroarch:
  enabled: true
  resources:
    limits:
      nvidia.com/gpu: "0"  # Sem GPU dedicada aqui se o Xorg/Sunshine já compartilham o contexto via variáveis de ambiente
    requests:
      nvidia.com/gpu: "0"
  volumeMounts:
    - name: roms
      mountPath: /home/retro/ROMs
    # - name: config
    #   mountPath: /home/retro/.config

xorg:
  resolution: "1920x1080"
  refreshrate: 60
  resources:
    limits:
      nvidia.com/gpu: "0"
    requests:
      nvidia.com/gpu: "0"

sunshine:
  enabled: true
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
  user: ""
  password: ""
  logLevel: "info"
  env:
    SUNSHINE_USER:
      valueFrom:
        secretKeyRef:
          name: games-on-whales-sec
          key: user
    SUNSHINE_PASS:
      valueFrom:
        secretKeyRef:
          name: games-on-whales-sec
          key: password

persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 3Gi
    storageClass: "local-path"
  
  roms:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 20Gi 
    mountPath: /home/retro/ROMs
    storageClass: "local-path"

service:
  main:
    type: LoadBalancer
  udp:
    type: LoadBalancer
