
steam:
  enabled: false
firefox:
  enabled: false


retroarch:
  enabled: true

graphic_resources:
  limits:
    nvidia.com/gpu: 1

xorg:
  resolution: "1920x1080"
  refreshrate: 60

sunshine:
  user: ""
  password: ""
  logLevel: "info"
  env:
    SUNSHINE_USER:
      valueFrom:
        secretKeyRef:
          name: games-on-whales-sec
          key: user
    SUNSHINE_PASS:
      valueFrom:
        secretKeyRef:
          name: games-on-whales-sec
          key: password

persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: "local-path"
  
  roms:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 30Gi 
    mountPath: /home/retro/ROMs
    storageClass: "local-path"

service:
  main:
    type: LoadBalancer
  udp:
    type: LoadBalancer