apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: gk-set-annotation-managged-by
spec:
  location: metadata.annotations."app.kubernetes.io/managed-by"
  match:
    scope: Namespaced
    namespaces: ["adguard","adguard-exporter","audiobookshelf","blackbox-exporter","cardsgo","default","discord2whatsapp-stack","duplicati-prom-exporter","frigate","grafana","grafana2whatsapp","m5-stick-proxmox-metrics","minecraft","n8n","prometheus","pve-exporter","speedtest-exporter","traefik-gateway"]
  parameters:
    assign:
      value: argocd
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: gk-set-annotation-owner
spec:
  location: metadata.annotations."app.kubernetes.io/owner"
  match:
    scope: Namespaced
    namespaces: ["adguard","adguard-exporter","audiobookshelf","blackbox-exporter","cardsgo","default","discord2whatsapp-stack","duplicati-prom-exporter","frigate","grafana","grafana2whatsapp","m5-stick-proxmox-metrics","minecraft","n8n","prometheus","pve-exporter","speedtest-exporter","traefik-gateway"]
  parameters:
    assign:
      value: aleixohome
