apiVersion: v1
kind: Service
metadata:
  name: duplicati-prom-exporter-svc
  namespace: duplicati-prom-exporter
spec:
  selector:
    app: duplicati-prom-exporter
  ports:
    - name: metrics
      port: 80
      targetPort: 5000
  type: ClusterIP
