apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cluster-auth-sa
  namespace: external-secrets 
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    vault:
      server: "http://vault-internal.hashicorp-vault.svc.cluster.local:8200" 
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cluster-wide-role"
          serviceAccountRef:
            name: "vault-cluster-auth-sa"
            namespace: "external-secrets" 
