apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: internal-lab

  sources:
    - repoURL: 'https://mojo2600.github.io/adguard-home-helm'
      targetRevision: 5.4.1
      chart: adguard-home
      helm:
        releaseName: adguard-home
        valueFiles:
          - $values/kubernetes/gitops/adguard-home/values.yaml

    # 2. Referência do Git para o values.yaml ($values)
    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      ref: values

  destination:
    name: in-cluster
    namespace: adguard-home

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
