apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: internal-lab

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.6.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/kubernetes/gitops/external-secrets/values.yaml

    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      ref: values

    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      path: kubernetes/gitops/external-secrets/deps/

  destination:
    name: in-cluster
    namespace: external-secrets # Namespace dedicado ao operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Altamente recomendado para o External Secrets devido ao tamanho dos CRDs
      - SkipDryRunOnMissingResource=true
