apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: games-on-whales
  namespace: argocd
spec:
  project: internal-lab

  sources:
    - repoURL: 'https://k8s-at-home.com/charts/'
      targetRevision: '*'
      chart: games-on-whales
      helm:
        releaseName: retro-gaming
        valueFiles:
          - $values/kubernetes/gitops/games-on-whales/values.yaml

    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      ref: values

  destination:
    name: in-cluster
    namespace: games-on-whales

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true