apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: internal-lab

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 60.0.2
      helm:
        releaseName: prometheus-stack
        valueFiles:
          - $values/kubernetes/gitops/kube-prometheus-stack/values.yaml

    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      ref: values

    - repoURL: git@github.com:AleixoLucas42/homelab-v3.git
      targetRevision: main
      path: kubernetes/gitops/kube-prometheus-stack/deps/

  destination:
    name: in-cluster
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
